### ISSUE TITLE
Way to distinguish between supported and unsupported emails

### ISSUE THREAD

**Issue by franciscolourenco** [bkonetzny/link-to-inbox#4]
Even when emails are not supported, both spec and url are populated, with guesswork. So for every non-supported email, you are sending users to random websites based on the domain of the email.

Is there a way to know if an email is supported?

**Comment by bkonetzny** [comment]
You can set the parameter `onlyMatched` to true and the library will only return valid matches. Otherwise you will get the fallback to the emails domain like you said.

**Comment by franciscolourenco** [comment]
Thanks, not in the readme :)
